[package]
name = "nstack"
version = "0.5.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"
description = "Arity 4 stack for the kelvin merkle toolkit"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/nstack"
keywords = ["merkle", "datastructure", "stack"]

[dependencies]
kelvin = { git = "https://github.com/dusk-network/kelvin", branch = "canonical_inside" }
canonical = "0.1.0"
canonical_derive = "0.1.0"
canonical_host = "0.1.0"
